name: flutter_china_stats_visualizer
description: "ChinaStatsVisualizer is a Flutter application designed to present monthly statistical data from the National Bureau of Statistics of China (NBS). It provides users with an intuitive interface to explore key economic and social indicators through interactive charts and tables. The application fetches data directly from the NBS API, ensuring accuracy and timeliness. Users can visualize trends, compare different indicators, and gain valuable insights into China's economic landscape."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_acrylic: ^1.1.0
  go_router: ^14.3.0
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  bitsdojo_window: ^0.1.6
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  excel: ^4.0.6
  sqflite_common_ffi: ^2.3.4
  path_provider: ^2.1.4
  logger: ^2.4.0
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  build_runner:
  custom_lint:
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/dashboard/
    - assets/images/illustration/
    - assets/logo/
    - assets/excel/M-Metrics.xlsx

